# -*- coding: utf-8 -*-
"""Untitled63.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c1qFeAoM_B5jT8p2KJm4j9a3XSmb8FhD
"""

# ==================== STEP 4: CALCUL DES SAVINGS ====================
print("\n" + "=" * 70)
print("💰 ÉTAPE 4: Calcul des Savings Générés")
print("=" * 70)

# Coût total par fournisseur
df['supplier_total_cost'] = df['unit_cost_total'] + df['freight_total_cost'] + df['non_quality_cost']

# Commandes en retard
df['late_orders'] = (1 - df['otd_per_po']) * df['po_volume_yearly']

# Coût total du portefeuille actuel
portfolio_cost_current = (df['supplier_total_cost'] * df['current_allocation']).sum()

# Calcul des savings par scénario
savings_results = {}

for scenario in ['conservative', 'aggressive', 'risk_mitigation']:
    # Coût total avec nouvelle allocation
    portfolio_cost_new = (df['supplier_total_cost'] * df[f'new_allocation_{scenario}']).sum()

    # Savings globaux
    savings_absolute = portfolio_cost_current - portfolio_cost_new
    savings_percent = (savings_absolute / portfolio_cost_current) * 100

    # Savings sur non-qualité
    nq_cost_current = (df['non_quality_cost'] * df['current_allocation']).sum()
    nq_cost_new = (df['non_quality_cost'] * df[f'new_allocation_{scenario}']).sum()
    savings_nq = nq_cost_current - nq_cost_new

    # Delta late purchase order
    late_current = (df['late_orders'] * df['current_allocation']).sum()
    late_new = (df['late_orders'] * df[f'new_allocation_{scenario}']).sum()
    delta_late = late_current - late_new

    savings_results[scenario] = {
        'portfolio_cost_current': portfolio_cost_current,
        'portfolio_cost_new': portfolio_cost_new,
        'savings_absolute': savings_absolute,
        'savings_percent': savings_percent,
        'savings_non_quality': savings_nq,
        'delta_late_orders': delta_late
    }

    print(f"\n🎯 Scenario: {scenario.upper()}")
    print(f"   Cost actual portfolio: ${portfolio_cost_current:,.2f}")
    print(f"   Cost optimized portfolio: ${portfolio_cost_new:,.2f}")
    print(f"   💵 Savings: ${savings_absolute:,.2f} ({savings_percent:+.2f}%)")
    print(f"   ✅ Non quality cost savings: ${savings_nq:,.2f}")
    print(f"   🚚 late orders reduction: {delta_late:,.0f} commandes")